Add solution to first lab
StoyanYanev/Web pull request #1
Opened 2020-02-19 16:35 UTC by StoyanYanev

2020-02-19 22:11 UTC, martinely95 requested changes

2020-02-19 22:11 UTC, martinely95 commented on 62240.html
> +    <a href="https://bg-bg.facebook.com/">Facebook</a>
Липсва отварянето на нов екран. https://iliasky.com/www/presentations/INTRO.html?read=1#15 предпоследното условие

2020-02-19 22:11 UTC, martinely95 commented on 62240.html
> +    <head>
Може да искате да добавите `<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">` в head частта заради кирилицата. Повече информация:

- https://stackoverflow.com/questions/22735993/html5-encoding-cyrillic

- https://www.w3schools.com/charsets/ref_html_utf8.asp

2020-02-19 22:12 UTC, martinely95 commented
Може да искате да пуснете файла на валидатор: https://validator.w3.org/

2020-02-23 13:18 UTC, martinely95 commented on 62240.html
> +    <head>
Furthermore, the meta tag for the charset will enhance your protection from XSS (Cross-Site Scripting) attacks. It is important that the browser is not left alone to guess the charset as some unexpected behaviour may be observed, especially with escaped characters. 
More info: 
https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A7-Cross-Site_Scripting_(XSS)  
https://owasp.org/www-project-cheat-sheets/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet

2020-02-26 15:38 UTC, tancheto commented on 62240.html
> +</html>
You can add lang attribute for example.

2020-02-26 16:13 UTC, martinely95 requested changes

2020-02-26 16:13 UTC, martinely95 commented on 62240.html
> +        <li>Спагети</li>
New cooment

2020-02-26 16:13 UTC, martinely95 commented on 62240.html
> +    <body>
Comment 2

2020-03-03 10:23 UTC, merged